import openpyxl, sys
sys.stdout.reconfigure(encoding='utf-8')

entries = [
    {
        'competition_ref': 'icr-identify-age-related-conditions',
        'title': 'ICR - Identifying Age-Related Conditions',
        'category': 'Featured', 'is_monetized': 'TRUE', 'n_teams': 6430, 'end_date': '2023-08-14',
        'target_type': 'binary', 'n_features': 56, 'feature_type_dominant': 'numeric',
        'has_categorical': 'TRUE', 'distribution_shift': 'TRUE',
        'finish_rank': 1, 'writeup_detail': 2,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'not_described',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'NN', 'cv_strategy': 'not_described', 'rare_class_handling': 'not_described',
        'ensemble_method': 'not_described',
        'fe_techniques': 'No FE (overfitting); multi-label CV strategy; reweighting probabilities at output',
        'models_used': 'NN', 'best_single_model': 'NN',
        'hyperparameter_tuning': 'not_described', 'original_data_usage': 'not_described',
    },
    {
        'competition_ref': 'playground-series-s4e7',
        'title': 'Binary Classification of Insurance Cross Selling',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 2234, 'end_date': '2024-07-31',
        'target_type': 'binary', 'feature_type_dominant': 'mixed',
        'has_categorical': 'TRUE', 'distribution_shift': 'not_described',
        'finish_rank': 1, 'writeup_detail': 3,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'not_described',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'ensemble', 'cv_strategy': 'stratified_kfold', 'rare_class_handling': 'not_described',
        'ensemble_method': 'stacking',
        'fe_techniques': 'Feature store (12 versions); component models on feature subsets (previously insured, vehicle damage); feature importance via CatBoost single-fold',
        'models_used': 'XGBoost, LightGBM, CatBoost, NN', 'best_single_model': 'CatBoost',
        'hyperparameter_tuning': 'not_described', 'original_data_usage': 'not_described',
    },
    {
        'competition_ref': 'playground-series-s5e3',
        'title': 'Binary Prediction with a Rainfall Dataset',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 4381, 'end_date': '2025-03-31',
        'target_type': 'binary', 'feature_type_dominant': 'numeric',
        'has_categorical': 'FALSE', 'distribution_shift': 'TRUE',
        'finish_rank': 1, 'writeup_detail': 3,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'not_described',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'ensemble', 'cv_strategy': 'grouped', 'rare_class_handling': 'not_described',
        'ensemble_method': 'blending',
        'fe_techniques': 'No FE; original data added as new columns via target mapping (merge_columns approach)',
        'models_used': 'XGBoost, CatBoost, TabPFN, LogisticRegression, SVC, SVR',
        'best_single_model': 'SVC',
        'hyperparameter_tuning': 'not_described', 'original_data_usage': 'merge_columns',
    },
    {
        'competition_ref': 'playground-series-s5e5',
        'title': 'Predict Calorie Expenditure',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 4316, 'end_date': '2025-05-31',
        'target_type': 'regression', 'feature_type_dominant': 'numeric',
        'has_categorical': 'TRUE', 'distribution_shift': 'not_described',
        'finish_rank': 1, 'writeup_detail': 3,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'target',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'ensemble', 'cv_strategy': 'kfold', 'rare_class_handling': 'not_described',
        'ensemble_method': 'hill_climbing',
        'fe_techniques': 'log1p transforms; product/division/sum/diff pairs; binned features (9 bins); groupby z-score features (26); residual modeling (NN on LR residuals, XGB on NN residuals); cuML TargetEncoder',
        'models_used': 'XGBoost, CatBoost, NN, LinearRegression', 'best_single_model': '',
        'hyperparameter_tuning': 'manual', 'original_data_usage': 'concat_rows',
    },
    {
        'competition_ref': 'playground-series-s5e12',
        'title': 'Diabetes Prediction Challenge',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 4206, 'end_date': '2025-12-31',
        'target_type': 'binary', 'feature_type_dominant': 'mixed',
        'has_categorical': 'TRUE', 'distribution_shift': 'TRUE',
        'finish_rank': 1, 'writeup_detail': 2,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'not_described',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'ensemble', 'cv_strategy': 'post_cutoff', 'rare_class_handling': 'not_described',
        'ensemble_method': 'stacking',
        'fe_techniques': 'Rank transformation; varied FE approaches across ~100 base models',
        'models_used': 'XGBoost, LightGBM, CatBoost, NN, Ridge, AutoML', 'best_single_model': '',
        'hyperparameter_tuning': 'not_described', 'original_data_usage': 'not_described',
    },
    {
        'competition_ref': 'playground-series-s5e10',
        'title': 'Predicting Road Accident Risk',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 4082, 'end_date': '2025-10-31',
        'target_type': 'regression', 'feature_type_dominant': 'mixed',
        'has_categorical': 'TRUE', 'distribution_shift': 'not_described',
        'finish_rank': 1, 'writeup_detail': 3,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'not_described',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'ensemble', 'cv_strategy': 'not_described', 'rare_class_handling': 'not_described',
        'ensemble_method': 'stacking',
        'fe_techniques': 'Autoencoder latent features; genetic programming features (11 GP); XGBoost residual boosting; multiple feature type representations (categorical/numerical/mixed)',
        'models_used': 'XGBoost, CatBoost, NN, Lasso, AutoGluon, Autoencoder', 'best_single_model': '',
        'hyperparameter_tuning': 'not_described', 'original_data_usage': 'not_described',
    },
    {
        'competition_ref': 'playground-series-s4e10',
        'title': 'Loan Approval Prediction',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 3858, 'end_date': '2024-10-31',
        'target_type': 'binary', 'feature_type_dominant': 'mixed',
        'has_categorical': 'TRUE', 'distribution_shift': 'not_described',
        'finish_rank': 1, 'writeup_detail': 2,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'not_described',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'ensemble', 'cv_strategy': 'not_described', 'rare_class_handling': 'not_described',
        'ensemble_method': 'stacking',
        'fe_techniques': 'Dual numeric+categorical feature representation; large max_bin values; original dataset included',
        'models_used': 'LightGBM, XGBoost, CatBoost, NN', 'best_single_model': 'CatBoost',
        'hyperparameter_tuning': 'optuna', 'original_data_usage': 'not_described',
    },
    {
        'competition_ref': 'playground-series-s5e11',
        'title': 'Predicting Loan Payback',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 3724, 'end_date': '2025-11-30',
        'target_type': 'binary', 'feature_type_dominant': 'mixed',
        'has_categorical': 'TRUE', 'distribution_shift': 'not_described',
        'finish_rank': 1, 'writeup_detail': 3,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'target',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'ensemble', 'cv_strategy': 'not_described', 'rare_class_handling': 'not_described',
        'ensemble_method': 'hill_climbing',
        'fe_techniques': 'Digit extraction from numericals; pairwise/triple/quadruple digit interactions + TE/CE; base feature pairs + TE/CE; quantile binning; categorical version of credit_score; TE with alternative targets',
        'models_used': 'XGBoost, LightGBM, CatBoost, NN, LogisticRegression, RandomForest, ExtraTrees',
        'best_single_model': 'XGBoost',
        'hyperparameter_tuning': 'none', 'original_data_usage': 'concat_rows',
    },
    {
        'competition_ref': 'playground-series-s4e1',
        'title': 'Binary Classification with a Bank Churn Dataset',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 3632, 'end_date': '2024-01-31',
        'target_type': 'binary', 'feature_type_dominant': 'mixed',
        'has_categorical': 'TRUE', 'distribution_shift': 'not_described',
        'finish_rank': 2, 'writeup_detail': 2,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'not_described',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'ensemble', 'cv_strategy': 'not_described', 'rare_class_handling': 'not_described',
        'ensemble_method': 'blending',
        'fe_techniques': 'Subset matching — all 1-10 element feature subsets checked against original dataset (~1000 binary indicators); CustomerId+Surname subset; post-processing probability shift',
        'models_used': 'LightGBM, AutoGluon', 'best_single_model': 'AutoGluon',
        'hyperparameter_tuning': 'none', 'original_data_usage': 'feature_lookup',
    },
    {
        'competition_ref': 'playground-series-s5e2',
        'title': 'Backpack Prediction Challenge',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 3393, 'end_date': '2025-02-28',
        'target_type': 'regression', 'feature_type_dominant': 'mixed',
        'has_categorical': 'TRUE', 'distribution_shift': 'not_described',
        'finish_rank': 1, 'writeup_detail': 3,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'ordinal',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'XGBoost', 'cv_strategy': 'not_described', 'rare_class_handling': 'not_described',
        'ensemble_method': 'none',
        'fe_techniques': 'Groupby aggregations (mean/std/count/min/max/nunique/skew); groupby histogram bins; groupby quantiles; NaN base-2 encoding; numerical rounding/binning; digit extraction from floats; categorical column combinations (all pairs); division features (ratios of aggregated features)',
        'models_used': 'XGBoost', 'best_single_model': 'XGBoost',
        'hyperparameter_tuning': 'not_described', 'original_data_usage': 'merge_columns',
    },
    {
        'competition_ref': 'playground-series-s5e8',
        'title': 'Binary Classification with a Bank Dataset',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 3365, 'end_date': '2025-08-31',
        'target_type': 'binary', 'feature_type_dominant': 'mixed',
        'has_categorical': 'TRUE', 'distribution_shift': 'not_described',
        'finish_rank': 2, 'writeup_detail': 2,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'target',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'ensemble', 'cv_strategy': 'not_described', 'rare_class_handling': 'not_described',
        'ensemble_method': 'stacking',
        'fe_techniques': 'TE/CE on feature bigrams (competition + original targets); products of numerical bigrams; cyclical features',
        'models_used': 'XGBoost, LightGBM, CatBoost, NN, RandomForest', 'best_single_model': '',
        'hyperparameter_tuning': 'not_described', 'original_data_usage': 'concat_rows',
    },
    {
        'competition_ref': 'playground-series-s5e4',
        'title': 'Predict Podcast Listening Time',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 3310, 'end_date': '2025-04-30',
        'target_type': 'regression', 'feature_type_dominant': 'mixed',
        'has_categorical': 'TRUE', 'distribution_shift': 'not_described',
        'finish_rank': 1, 'writeup_detail': 3,
        'missing_data_strategy': 'model', 'encoding_strategy': 'not_described',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'ensemble', 'cv_strategy': 'kfold', 'rare_class_handling': 'not_described',
        'ensemble_method': 'stacking',
        'fe_techniques': 'Target ratio transformation (target/Episode_Length); Episode_Length imputation via model; pseudo labeling (train+test); residual boosting (GBDT on Lasso/SVR/MLP residuals); 6000 features for linear models; diverse feature sets per model',
        'models_used': 'XGBoost, LightGBM, NN, Lasso, SVR, KNN, RandomForest, AutoGluon', 'best_single_model': '',
        'hyperparameter_tuning': 'manual', 'original_data_usage': 'not_described',
    },
    {
        'competition_ref': 'playground-series-s4e9',
        'title': 'Regression of Used Car Prices',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 3066, 'end_date': '2024-09-30',
        'target_type': 'regression', 'feature_type_dominant': 'mixed',
        'has_categorical': 'TRUE', 'distribution_shift': 'not_described',
        'finish_rank': 1, 'writeup_detail': 3,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'target',
        'outlier_treatment': 'clip', 'scaling': 'not_described',
        'primary_model': 'ensemble', 'cv_strategy': 'kfold', 'rare_class_handling': 'not_described',
        'ensemble_method': 'stacking',
        'fe_techniques': 'CatBoost classifier OOF as feature for LGBM; SVR OOF as NN feature; median target encoding (leakfree per fold); rare category grouping; outlier price binning via IQR',
        'models_used': 'LightGBM, CatBoost, SVR, NN, XGBoost, AutoGluon', 'best_single_model': '',
        'hyperparameter_tuning': 'optuna', 'original_data_usage': 'concat_rows',
    },
    {
        'competition_ref': 'playground-series-s4e5',
        'title': 'Regression with a Flood Prediction Dataset',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 2788, 'end_date': '2024-05-31',
        'target_type': 'regression', 'feature_type_dominant': 'numeric',
        'has_categorical': 'FALSE', 'distribution_shift': 'not_described',
        'finish_rank': 1, 'writeup_detail': 2,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'target',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'ensemble', 'cv_strategy': 'kfold', 'rare_class_handling': 'not_described',
        'ensemble_method': 'stacking',
        'fe_techniques': 'Row-wise statistics (sum/std/max); sorted features; count threshold features (nb_sup6/7/8); target encoding on row sum; target transformation (subtract feature mean x0.1); permutation + backward feature selection',
        'models_used': 'XGBoost, LightGBM, CatBoost, AutoGluon', 'best_single_model': '',
        'hyperparameter_tuning': 'optuna', 'original_data_usage': 'not_described',
    },
    {
        'competition_ref': 'playground-series-s4e11',
        'title': 'Exploring Mental Health Data',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 2685, 'end_date': '2024-11-30',
        'target_type': 'binary', 'feature_type_dominant': 'mixed',
        'has_categorical': 'TRUE', 'distribution_shift': 'not_described',
        'finish_rank': 1, 'writeup_detail': 2,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'not_described',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'ensemble', 'cv_strategy': 'not_described', 'rare_class_handling': 'not_described',
        'ensemble_method': 'stacking',
        'fe_techniques': 'None',
        'models_used': 'XGBoost, LightGBM, AutoGluon', 'best_single_model': 'AutoGluon',
        'hyperparameter_tuning': 'not_described', 'original_data_usage': 'concat_rows',
    },
    {
        'competition_ref': 'playground-series-s5e6',
        'title': 'Predicting Optimal Fertilizers',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 2648, 'end_date': '2025-06-30',
        'target_type': 'multiclass', 'feature_type_dominant': 'mixed',
        'has_categorical': 'TRUE', 'distribution_shift': 'not_described',
        'finish_rank': 1, 'writeup_detail': 3,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'target',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'ensemble', 'cv_strategy': 'stratified_kfold', 'rare_class_handling': 'not_described',
        'ensemble_method': 'hill_climbing',
        'fe_techniques': 'All pairs/triples/quadruples of 8 features (162 combos); TE of 162 combos x7 binary targets (2268 cols); TE using original dataset; residual boosting (XGB over LR base margin); pseudo labeling; repeated KFold seed averaging; retrain on 100% data',
        'models_used': 'XGBoost, LightGBM, CatBoost, NN, LinearRegression, KNN', 'best_single_model': '',
        'hyperparameter_tuning': 'manual', 'original_data_usage': 'concat_rows, merge_columns',
    },
    {
        'competition_ref': 'playground-series-s4e8',
        'title': 'Binary Prediction of Poisonous Mushrooms',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 2422, 'end_date': '2024-08-31',
        'target_type': 'binary', 'feature_type_dominant': 'mixed',
        'has_categorical': 'TRUE', 'distribution_shift': 'not_described',
        'finish_rank': 1, 'writeup_detail': 2,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'not_described',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'ensemble', 'cv_strategy': 'not_described', 'rare_class_handling': 'not_described',
        'ensemble_method': 'stacking',
        'fe_techniques': 'Original dataset poisonous probability as engineered feature; confident disagreement overwriting (predictions >0.99 threshold)',
        'models_used': 'LightGBM, XGBoost, CatBoost, RandomForest, ExtraTrees, AutoGluon',
        'best_single_model': 'XGBoost',
        'hyperparameter_tuning': 'not_described', 'original_data_usage': 'concat_rows',
    },
    {
        'competition_ref': 'playground-series-s4e12',
        'title': 'Regression with an Insurance Dataset',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 2390, 'end_date': '2024-12-31',
        'target_type': 'regression', 'feature_type_dominant': 'mixed',
        'has_categorical': 'TRUE', 'distribution_shift': 'not_described',
        'finish_rank': 1, 'writeup_detail': 3,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'target',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'XGBoost', 'cv_strategy': 'kfold', 'rare_class_handling': 'not_described',
        'ensemble_method': 'none',
        'fe_techniques': 'Label encoding; TE (mean/median/min/max/nunique) + CE per column; column combinations (2-6 way); treating numerics as categorical + TE/CE; Policy Start Date decomposition; GPU-accelerated search of 145K+ combinations -> 170 kept',
        'models_used': 'XGBoost', 'best_single_model': 'XGBoost',
        'hyperparameter_tuning': 'not_described', 'original_data_usage': 'not_described',
    },
    {
        'competition_ref': 'playground-series-s4e3',
        'title': 'Steel Plate Defect Prediction',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 2199, 'end_date': '2024-03-31',
        'target_type': 'multiclass', 'feature_type_dominant': 'numeric',
        'has_categorical': 'FALSE', 'distribution_shift': 'not_described',
        'finish_rank': 2, 'writeup_detail': 3,
        'missing_data_strategy': 'drop', 'encoding_strategy': 'not_described',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'ensemble', 'cv_strategy': 'kfold', 'rare_class_handling': 'not_described',
        'ensemble_method': 'blending',
        'fe_techniques': 'Ratio features (length/thickness); range x area interaction; min-max normalized thickness feature; feature dropping via CV + feature importance + correlation',
        'models_used': 'XGBoost, LightGBM, CatBoost, HistGB', 'best_single_model': '',
        'hyperparameter_tuning': 'optuna', 'original_data_usage': 'concat_rows',
    },
    {
        'competition_ref': 'playground-series-s3e24',
        'title': 'Binary Prediction of Smoker Status using Bio-Signals',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 1908, 'end_date': '2023-12-31',
        'target_type': 'binary', 'feature_type_dominant': 'numeric',
        'has_categorical': 'FALSE', 'distribution_shift': 'not_described',
        'finish_rank': 3, 'writeup_detail': 2,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'not_described',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'ensemble', 'cv_strategy': 'stratified_kfold', 'rare_class_handling': 'not_described',
        'ensemble_method': 'blending',
        'fe_techniques': 'Brute-force feature combinations (80-120 kept); permutation importance for feature pruning',
        'models_used': 'LightGBM, XGBoost, CatBoost, RandomForest, LogisticRegression, TabNet, NN, GAM',
        'best_single_model': '',
        'hyperparameter_tuning': 'optuna', 'original_data_usage': 'concat_rows',
    },
    {
        'competition_ref': 'playground-series-s3e23',
        'title': 'Binary Classification with a Software Defects Dataset',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 1702, 'end_date': '2023-11-30',
        'target_type': 'binary', 'feature_type_dominant': 'numeric',
        'has_categorical': 'FALSE', 'distribution_shift': 'not_described',
        'finish_rank': 2, 'writeup_detail': 3,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'not_described',
        'outlier_treatment': 'not_described', 'scaling': 'log',
        'primary_model': 'ensemble', 'cv_strategy': 'not_described', 'rare_class_handling': 'not_described',
        'ensemble_method': 'hill_climbing',
        'fe_techniques': 'Log transformation of all features (core improvement); PCA/t-SNE/clustering tried but failed',
        'models_used': 'LightGBM, XGBoost, CatBoost, RandomForest, ExtraTrees, HistGB, LogisticRegression, NN',
        'best_single_model': '',
        'hyperparameter_tuning': 'not_described', 'original_data_usage': 'not_described',
    },
    {
        'competition_ref': 'playground-series-s3e14',
        'title': 'Regression with a Wild Blueberry Yield Dataset',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 1875, 'end_date': '2023-07-31',
        'target_type': 'regression', 'feature_type_dominant': 'numeric',
        'has_categorical': 'FALSE', 'distribution_shift': 'not_described',
        'finish_rank': 1, 'writeup_detail': 2,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'not_described',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'ensemble', 'cv_strategy': 'not_described', 'rare_class_handling': 'not_described',
        'ensemble_method': 'stacking',
        'fe_techniques': 'Post-processing: match test rows to original dataset by fruitset+fruitmass key -> assign original yield values; automated matching script (2073 test samples x 776 unique yields)',
        'models_used': 'not_described', 'best_single_model': '',
        'hyperparameter_tuning': 'not_described', 'original_data_usage': 'feature_lookup',
    },
    {
        'competition_ref': 'playground-series-s3e26',
        'title': 'Multi-Class Prediction of Cirrhosis Outcomes',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 1661, 'end_date': '2024-01-01',
        'target_type': 'multiclass', 'feature_type_dominant': 'mixed',
        'has_categorical': 'TRUE', 'distribution_shift': 'not_described',
        'finish_rank': 2, 'writeup_detail': 2,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'OHE',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'ensemble', 'cv_strategy': 'not_described', 'rare_class_handling': 'not_described',
        'ensemble_method': 'stacking',
        'fe_techniques': 'Piecewise linear encoding (PLE) for continuous features; embedding layers for categorical features (edema, stage)',
        'models_used': 'XGBoost, LightGBM, NN', 'best_single_model': '',
        'hyperparameter_tuning': 'optuna', 'original_data_usage': 'not_described',
    },
    {
        'competition_ref': 'playground-series-s3e16',
        'title': 'Regression with a Crab Age Dataset',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 1429, 'end_date': '2023-08-31',
        'target_type': 'regression', 'feature_type_dominant': 'mixed',
        'has_categorical': 'TRUE', 'distribution_shift': 'not_described',
        'finish_rank': 3, 'writeup_detail': 2,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'not_described',
        'outlier_treatment': 'not_described', 'scaling': 'log',
        'primary_model': 'ensemble', 'cv_strategy': 'stratified_kfold', 'rare_class_handling': 'not_described',
        'ensemble_method': 'stacking',
        'fe_techniques': 'Domain features (meat yield/surface area/weight ratios/pseudo BMI/viscera ratio); log transform on weight; post-processing (round to nearest integer); feature subset selection (6-10 features per model)',
        'models_used': 'XGBoost, LightGBM, CatBoost, HistGB', 'best_single_model': '',
        'hyperparameter_tuning': 'optuna', 'original_data_usage': 'concat_rows',
    },
    {
        'competition_ref': 'playground-series-s3e17',
        'title': 'Binary Classification of Machine Failures',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 1502, 'end_date': '2023-09-30',
        'target_type': 'binary', 'feature_type_dominant': 'numeric',
        'has_categorical': 'TRUE', 'distribution_shift': 'not_described',
        'finish_rank': 3, 'writeup_detail': 1,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'not_described',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'ensemble', 'cv_strategy': 'not_described', 'rare_class_handling': 'not_described',
        'ensemble_method': 'stacking',
        'fe_techniques': 'None described — AutoML handles internally',
        'models_used': 'AutoML', 'best_single_model': '',
        'hyperparameter_tuning': 'not_described', 'original_data_usage': 'not_described',
    },
    {
        'competition_ref': 'playground-series-s3e11',
        'title': 'Regression with a Tabular Media Campaign Cost Dataset',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 952, 'end_date': '2023-06-15',
        'target_type': 'regression', 'feature_type_dominant': 'mixed',
        'has_categorical': 'TRUE', 'distribution_shift': 'FALSE',
        'finish_rank': 1, 'writeup_detail': 3,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'not_described',
        'outlier_treatment': 'not_described', 'scaling': 'log',
        'primary_model': 'ensemble', 'cv_strategy': 'not_described', 'rare_class_handling': 'not_described',
        'ensemble_method': 'blending',
        'fe_techniques': 'Feature subset selection across models; duplicate grouping (360K->3000 groups); log1p target transformation; store_sqft treated as categorical',
        'models_used': 'LightGBM, XGBoost, CatBoost, RandomForest, ExtraTrees, NN', 'best_single_model': '',
        'hyperparameter_tuning': 'not_described', 'original_data_usage': 'concat_rows',
    },
    {
        'competition_ref': 'playground-series-s3e13',
        'title': 'Classification with a Tabular Vector Borne Disease Dataset',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 934, 'end_date': '2023-07-15',
        'target_type': 'multiclass', 'feature_type_dominant': 'numeric',
        'has_categorical': 'FALSE', 'distribution_shift': 'not_described',
        'finish_rank': 1, 'writeup_detail': 1,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'not_described',
        'outlier_treatment': 'not_described', 'scaling': 'standard',
        'primary_model': 'ensemble', 'cv_strategy': 'not_described', 'rare_class_handling': 'not_described',
        'ensemble_method': 'blending',
        'fe_techniques': 'None',
        'models_used': 'LightGBM, NN, Autoencoder', 'best_single_model': '',
        'hyperparameter_tuning': 'none', 'original_data_usage': 'not_described',
    },
    {
        'competition_ref': 'playground-series-s3e5',
        'title': 'Ordinal Regression with a Tabular Wine Quality Dataset',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 901, 'end_date': '2023-03-31',
        'target_type': 'multiclass', 'feature_type_dominant': 'numeric',
        'has_categorical': 'FALSE', 'distribution_shift': 'FALSE',
        'finish_rank': 1, 'writeup_detail': 2,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'not_described',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'XGBoost', 'cv_strategy': 'stratified_kfold', 'rare_class_handling': 'not_described',
        'ensemble_method': 'none',
        'fe_techniques': 'None — FE tried but worsened CV; post-processing with OptimizedRounder for ordinal class cutoffs',
        'models_used': 'XGBoost', 'best_single_model': 'XGBoost',
        'hyperparameter_tuning': 'optuna', 'original_data_usage': 'not_used',
    },
    {
        'competition_ref': 'playground-series-s3e10',
        'title': 'Binary Classification with a Tabular Pulsar Dataset',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 807, 'end_date': '2023-05-31',
        'target_type': 'binary', 'feature_type_dominant': 'numeric',
        'has_categorical': 'FALSE', 'distribution_shift': 'not_described',
        'finish_rank': 1, 'writeup_detail': 2,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'not_described',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'other', 'cv_strategy': 'not_described', 'rare_class_handling': 'not_described',
        'ensemble_method': 'stacking',
        'fe_techniques': 'XGBoost predictions as GAM input features; Lasso predictions as GAM input features; interaction terms in GAM',
        'models_used': 'GAM, XGBoost, Lasso', 'best_single_model': 'GAM',
        'hyperparameter_tuning': 'none', 'original_data_usage': 'not_described',
    },
    {
        'competition_ref': 'playground-series-s3e9',
        'title': 'Regression with a Tabular Concrete Strength Dataset',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 765, 'end_date': '2023-05-15',
        'target_type': 'regression', 'feature_type_dominant': 'numeric',
        'has_categorical': 'FALSE', 'distribution_shift': 'not_described',
        'finish_rank': 1, 'writeup_detail': 3,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'target',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'ensemble', 'cv_strategy': 'kfold', 'rare_class_handling': 'not_described',
        'ensemble_method': 'blending',
        'fe_techniques': 'Nonlinear features for linear regression (from partial dependence plots); feature selection by CV; target encoding of AgeInDays (treated as categorical)',
        'models_used': 'LightGBM, GradientBoosting, RandomForest, LinearRegression', 'best_single_model': '',
        'hyperparameter_tuning': 'manual', 'original_data_usage': 'not_described',
    },
    {
        'competition_ref': 'playground-series-s3e8',
        'title': 'Regression with a Tabular Gemstone Price Dataset',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 734, 'end_date': '2023-04-30',
        'target_type': 'regression', 'feature_type_dominant': 'mixed',
        'has_categorical': 'TRUE', 'distribution_shift': 'not_described',
        'finish_rank': 2, 'writeup_detail': 2,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'ordinal',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'ensemble', 'cv_strategy': 'kfold', 'rare_class_handling': 'not_described',
        'ensemble_method': 'stacking',
        'fe_techniques': 'Ordinal encoding of gemstone quality categoricals; aspect ratio features; carat x aspect ratio interaction; encoding methodology comparison via CV',
        'models_used': 'XGBoost, LightGBM, CatBoost, Ridge, NN', 'best_single_model': '',
        'hyperparameter_tuning': 'not_described', 'original_data_usage': 'concat_rows',
    },
    {
        'competition_ref': 'playground-series-s3e6',
        'title': 'Regression with a Tabular Paris Housing Price Dataset',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 703, 'end_date': '2023-04-15',
        'target_type': 'regression', 'feature_type_dominant': 'numeric',
        'has_categorical': 'FALSE', 'distribution_shift': 'not_described',
        'finish_rank': 3, 'writeup_detail': 2,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'not_described',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'ensemble', 'cv_strategy': 'kfold', 'rare_class_handling': 'not_described',
        'ensemble_method': 'stacking',
        'fe_techniques': 'Permutation importance for feature selection (per model separately)',
        'models_used': 'XGBoost, CatBoost, RandomForest, LightGBM', 'best_single_model': '',
        'hyperparameter_tuning': 'not_described', 'original_data_usage': 'concat_rows',
    },
    {
        'competition_ref': 'playground-series-s3e1',
        'title': 'Regression with a Tabular California Housing Dataset',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 689, 'end_date': '2023-01-31',
        'target_type': 'regression', 'feature_type_dominant': 'numeric',
        'has_categorical': 'FALSE', 'distribution_shift': 'not_described',
        'finish_rank': 1, 'writeup_detail': 1,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'not_described',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'ensemble', 'cv_strategy': 'kfold', 'rare_class_handling': 'not_described',
        'ensemble_method': 'stacking',
        'fe_techniques': 'Coordinate-based geographic features (from public notebook)',
        'models_used': 'XGBoost, LightGBM, CatBoost, RandomForest, NN', 'best_single_model': '',
        'hyperparameter_tuning': 'not_described', 'original_data_usage': 'not_described',
    },
    {
        'competition_ref': 'playground-series-s3e7',
        'title': 'Binary Classification with a Tabular Reservation Cancellation Dataset',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 678, 'end_date': '2023-04-30',
        'target_type': 'binary', 'feature_type_dominant': 'mixed',
        'has_categorical': 'TRUE', 'distribution_shift': 'not_described',
        'finish_rank': 1, 'writeup_detail': 2,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'OHE',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'ensemble', 'cv_strategy': 'stratified_kfold', 'rare_class_handling': 'not_described',
        'ensemble_method': 'blending',
        'fe_techniques': 'Categorical feature identification; OHE vs native encoding comparison; duplicate/leakage exploitation (opposite label assignment; predict 0.5 for test duplicates); adversarial validation to filter original dataset; removal of train duplicates with test counterparts',
        'models_used': 'XGBoost, LightGBM', 'best_single_model': '',
        'hyperparameter_tuning': 'manual', 'original_data_usage': 'concat_rows',
    },
    {
        'competition_ref': 'playground-series-s3e3',
        'title': 'Binary Classification with a Tabular Employee Attrition Dataset',
        'category': 'Playground', 'is_monetized': 'FALSE', 'n_teams': 665, 'end_date': '2023-02-28',
        'target_type': 'binary', 'feature_type_dominant': 'mixed',
        'has_categorical': 'TRUE', 'distribution_shift': 'not_described',
        'finish_rank': 1, 'writeup_detail': 1,
        'missing_data_strategy': 'not_described', 'encoding_strategy': 'not_described',
        'outlier_treatment': 'not_described', 'scaling': 'not_described',
        'primary_model': 'ensemble', 'cv_strategy': 'not_described', 'rare_class_handling': 'not_described',
        'ensemble_method': 'not_described',
        'fe_techniques': 'Domain-driven risk flags (age<34; hourly rate<60; distance>=20; tenure<4 years; job hopper); composite AttritionRisk score; MonthlyIncome/Age ratio; AverageTenure (TotalWorkingYears/NumCompaniesWorked)',
        'models_used': 'XGBoost, LightGBM, CatBoost', 'best_single_model': '',
        'hyperparameter_tuning': 'not_described', 'original_data_usage': 'not_described',
    },
]

# Write to Excel
wb = openpyxl.load_workbook('data/kaggle_meta_analysis.xlsx')
ws = wb['Competition Data']
headers = [cell.value for cell in ws[1]]

for entry in entries:
    row = [entry.get(h, '') for h in headers]
    ws.append(row)

wb.save('data/kaggle_meta_analysis.xlsx')
print(f'Written {len(entries)} entries to kaggle_meta_analysis.xlsx')
print(f'Total rows now: {ws.max_row}')
